name: ff_navigation_bar
description: Configurable bottom navigation bar with raised highlight and shadow
version: 0.1.6
homepage: https://github.com/55Builds/Flutter-FFNavigationBar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

